# Generated by Django 4.2.4 on 2023-09-09 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reset',
            old_name='email',
            new_name='phone',
        ),
    ]
