# Generated by Django 4.2.4 on 2023-08-27 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonial',
            old_name='profesion_en',
            new_name='profession_en',
        ),
        migrations.RenameField(
            model_name='testimonial',
            old_name='profesion_ru',
            new_name='profession_ru',
        ),
        migrations.RenameField(
            model_name='testimonial',
            old_name='profesion_uz',
            new_name='profession_uz',
        ),
    ]
