# Generated by Django 4.2.4 on 2023-08-27 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0003_rename_profesion_en_testimonial_profession_en_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FAQ',
            new_name='QA',
        ),
    ]
