# Generated by Django 4.2.4 on 2023-08-28 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0004_rename_faq_qa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='course',
            name='start_time',
        ),
        migrations.AddField(
            model_name='course',
            name='time_interval',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
