# Generated by Django 4.2.4 on 2023-08-29 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0006_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='platform',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
