# Generated by Django 4.2.4 on 2023-08-31 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0010_alter_student_district_alter_student_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='district',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='region',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
