# Generated by Django 4.2.4 on 2023-08-31 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0011_alter_student_district_alter_student_region'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='region',
            new_name='region1',
        ),
    ]
