# Generated by Django 4.2.4 on 2023-08-31 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0012_rename_region_student_region1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='district',
        ),
        migrations.RemoveField(
            model_name='student',
            name='region1',
        ),
    ]
