# Generated by Django 4.2.4 on 2023-08-31 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0013_remove_student_district_remove_student_region1'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='control.district'),
        ),
        migrations.AddField(
            model_name='student',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='control.region'),
        ),
    ]
