# Generated by Django 4.2.4 on 2023-08-31 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0014_student_district_student_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='birthday',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
