# Generated by Django 4.2.4 on 2023-08-31 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0015_alter_student_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='certificate_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
