# Generated by Django 4.2.4 on 2023-08-31 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0016_student_certificate_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(blank=True, choices=[('registered', 'Registered'), ('completed', 'Completed')], max_length=100, null=True),
        ),
    ]
