# Generated by Django 4.2.4 on 2023-08-31 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0017_alter_student_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
