# Generated by Django 4.2.4 on 2023-08-31 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0018_alter_student_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
