# Generated by Django 4.2.4 on 2023-09-01 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0019_alter_district_title_alter_region_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='QFE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.TextField()),
                ('answered', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-date_created',),
            },
        ),
    ]
