# Generated by Django 4.2.4 on 2023-09-04 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0020_qfe'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='tgender',
            field=models.CharField(blank=True, choices=[('male', 'Erkak'), ('female', 'Ayol')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='tstatus',
            field=models.CharField(choices=[('start', "Ro'yxatdan o'tmoqda"), ('end', "Ro'yxatdan o'tgan")], default='start', max_length=255),
        ),
    ]
