# Generated by Django 4.2.4 on 2023-09-05 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0021_student_tgender_student_tstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='pdf_created',
            field=models.BooleanField(default=False),
        ),
    ]
