# Generated by Django 4.2.4 on 2023-09-09 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0022_student_completed_student_pdf_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='direction_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='expert',
            name='direction_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='expert',
            name='direction_uz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
