# Generated by Django 4.2.4 on 2023-09-09 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0023_expert_direction_en_expert_direction_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qfe',
            name='category',
        ),
        migrations.AddField(
            model_name='qfe',
            name='expert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='control.expert'),
        ),
    ]
