# Generated by Django 4.2.4 on 2023-09-18 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0025_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date_created',
            field=models.DateTimeField(),
        ),
    ]
