# Generated by Django 4.2.4 on 2023-09-18 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0026_alter_student_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
