# Generated by Django 4.2.4 on 2023-09-18 21:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0027_alter_student_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 9, 18, 21, 15, 52, 690610, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
