# Generated by Django 4.2.4 on 2023-09-19 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0029_excel'),
    ]

    operations = [
        migrations.AddField(
            model_name='excel',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='control.district'),
        ),
    ]
