# Generated by Django 4.2.4 on 2023-09-19 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0030_excel_district'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='excel',
            options={'ordering': ('download',)},
        ),
    ]
