# Generated by Django 4.2.4 on 2024-02-08 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0033_book_delete_library'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='fa',
            field=models.CharField(default='000000', max_length=255),
        ),
    ]
