# Generated by Django 4.2.4 on 2024-02-08 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0034_student_fa'),
    ]

    operations = [
        migrations.CreateModel(
            name='FA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='fa',
        ),
    ]
