# Generated by Django 4.2.4 on 2024-02-08 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0035_fa_remove_student_fa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fa',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
