# Generated by Django 4.2.4 on 2024-02-21 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0036_alter_fa_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='inn',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
