# Generated by Django 4.2.4 on 2024-02-21 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0037_student_inn'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='date_confirmed',
            field=models.DateField(blank=True, null=True),
        ),
    ]
