# Generated by Django 4.2.4 on 2024-04-28 08:56

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0040_categorybook_book_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='about_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[1060, 800], upload_to='photos/'),
        ),
    ]
