# Generated by Django 4.2.4 on 2025-09-24 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0041_office_about_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorybook',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
