# Generated by Django 4.2.4 on 2025-09-24 06:55

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0042_categorybook_title_en'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(blank=True, max_length=500, null=True)),
                ('title_uz', models.CharField(blank=True, max_length=500, null=True)),
                ('title_en', models.CharField(blank=True, max_length=500, null=True)),
                ('priority', models.IntegerField(default=1)),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[550, 550], upload_to='videos/')),
                ('url', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'ordering': ('priority',),
            },
        ),
    ]
