# Generated by Django 4.2.4 on 2025-10-10 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0043_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchForMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('lat', models.CharField(max_length=255)),
                ('lon', models.CharField(max_length=255)),
            ],
        ),
    ]
