# Generated by Django 4.2.4 on 2025-10-10 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0044_branchformap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branchformap',
            name='name',
        ),
        migrations.AddField(
            model_name='branchformap',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='branchformap',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
