# Generated by Django 4.2.4 on 2025-10-10 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0045_remove_branchformap_name_branchformap_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='group',
            field=models.CharField(choices=[('previous', 'Предыдущие сотрудничавшие эксперты'), ('current', 'Текущие соавторы')], default='current', max_length=20),
        ),
    ]
