# Generated by Django 4.2.4 on 2025-10-10 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0046_expert_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expert',
            name='group',
            field=models.CharField(choices=[('previous', 'Бывший коллега'), ('current', 'Текущий коллега')], default='current', max_length=20),
        ),
    ]
