# Generated by Django 4.2.4 on 2025-10-10 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0047_alter_expert_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(blank=True, max_length=500, null=True)),
                ('title_uz', models.CharField(blank=True, max_length=500, null=True)),
                ('title_en', models.CharField(blank=True, max_length=500, null=True)),
                ('content_ru', models.TextField()),
                ('content_uz', models.TextField()),
                ('content_en', models.TextField()),
                ('date', models.DateField()),
            ],
            options={
                'ordering': ('date',),
            },
        ),
    ]
