# Generated by Django 4.2.4 on 2025-10-10 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0048_event'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Event',
            new_name='Program',
        ),
    ]
